#访问地址，端口
server:
  servlet:
    context-path: /
  url: localhost
  port: 8080
  #配置tomcat
  tomcat:
    max-threads: 300
    max-connections: 20000

#连接池
spring:
  shardingsphere:
    datasource:
      names: do1
      do1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/exceltosql?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
    sharding:
      tables:
        zyfx:
          actual-data-nodes: do1.zyfx_$->{["xjj","cjl","wjc","bcb","hy","dyxj","mlxd","xym","nfq","wdd"]}
          table-strategy:
            standard:
              sharding-column: juZhan
              precise-algorithm-class-name: com.unicom.excelforunicom.base.sharding.ModuloTableShardingAlgorithm
      default-data-source-name: do1
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true
#配置上传文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#开发环境swagger开启
swagger:
  enabled: true

#mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    interceptors: {com.unicom.excelforunicom.base.sharding.TableShardInterceptor,com.unicom.excelforunicom.base.sharding.selectTableShardInterceptor}

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  row-bounds-with-count: false
  reasonable: true

  #指定log4j2的配置文件
logging:
  config: classpath:log4j2-dev.xml

titles:
  zyfx:
    excelTitle:
      - "光缆"
      - "纤芯"
      - "端子名称"
      - "端子业务状态"
      - "专业类别"
      - "业务类别"
      - "业务号码"
      - "业务名称"
      - "现场标签名称"
      - "对应位置"
      - "设备间内跳接位置"
      - "光交位置"
      - "光交跳接"
      - "配线光缆名称"
      - "变更日期"
      - ""
      - ""
      - "设备名称"
      - "模块名称"
      - "盘"
      - ""
      - "端子名称1"
      - ""
      - "局站"
      - "机房"
      - "设备ID"
      - "端子ID"
  jh:
    excelTitle:
      - "端子名称"
      - "端子业务状态"
      - "专业类别"
      - "业务类别"
      - "业务号码"
      - "业务名称"
      - "现场标签名称"
      - "对应位置"
      - "设备间内跳接位置"
      - "变更日期"
      - "局站"